// <auto-generated />
using System;
using GoPillBox.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GoPillBox.Migrations
{
    [DbContext(typeof(GoPillBoxDbContext))]
    [Migration("20231115233529_CorrectedNamesAndTypes")]
    partial class CorrectedNamesAndTypes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GoPillBox.Models.AlarmEvent", b =>
                {
                    b.Property<int>("AlarmEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("alarm_event_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AlarmEventId"));

                    b.Property<int>("CurrentState")
                        .HasColumnType("integer")
                        .HasColumnName("current_state");

                    b.Property<DateTime>("EventTimeStamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("event_time_stamp");

                    b.Property<int>("MedicationInTreatmentId")
                        .HasColumnType("integer")
                        .HasColumnName("medication_in_treatment_id");

                    b.Property<int>("PostponedForInMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("postponed_for_in_minutes");

                    b.HasKey("AlarmEventId");

                    b.ToTable("alarm_events");
                });

            modelBuilder.Entity("GoPillBox.Models.MedicationInTreatment", b =>
                {
                    b.Property<int>("MedicationInTreatmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("medication_in_treatment_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MedicationInTreatmentId"));

                    b.Property<float>("Dose")
                        .HasColumnType("real")
                        .HasColumnName("dose");

                    b.Property<string>("DoseUnitOfMesure")
                        .IsRequired()
                        .HasColumnType("character varying(20)")
                        .HasColumnName("dose_unit_of_mesure");

                    b.Property<float>("DosingFrequencyInHours")
                        .HasColumnType("real")
                        .HasColumnName("dosing_frequency_in_hours");

                    b.Property<string>("MedicNotes")
                        .IsRequired()
                        .HasColumnType("character varying(350)")
                        .HasColumnName("medic_notes");

                    b.Property<string>("MedicationName")
                        .IsRequired()
                        .HasColumnType("character varying(70)")
                        .HasColumnName("medication_name");

                    b.Property<int>("TimeInTreatmentInDays")
                        .HasColumnType("integer")
                        .HasColumnName("time_in_treatment_in_days");

                    b.Property<int>("TreatmentId")
                        .HasColumnType("integer")
                        .HasColumnName("treatment_id");

                    b.HasKey("MedicationInTreatmentId");

                    b.ToTable("medication_in_treatments");
                });

            modelBuilder.Entity("GoPillBox.Models.Treatment", b =>
                {
                    b.Property<int>("TreatmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("treatment_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TreatmentId"));

                    b.Property<string>("GeneralDescription")
                        .IsRequired()
                        .HasColumnType("character varying(250)")
                        .HasColumnName("general_description");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("TreatmentId");

                    b.ToTable("treatments");
                });

            modelBuilder.Entity("GoPillBox.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("character varying(50)")
                        .HasColumnName("password");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("character varying(50)")
                        .HasColumnName("user_name");

                    b.HasKey("UserId");

                    b.ToTable("users");
                });
#pragma warning restore 612, 618
        }
    }
}
